---
# tasks file for helloworld

- name: Copying the application file
  copy:
    src: helloworld.js
    dest: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    mode: 0644
  notify: restart helloworld

- name: Copying the upstart file
  copy:
    src: helloworld.conf
    dest: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    mode: 0644

- name: Starting the helloworld node service
  service:
      name: helloworld
      state: started
      